### ISSUE TITLE
Number of solutions is a float

### ISSUE THREAD

**Issue by JonahDW** [SpheMakh/msutils#28]
Came across this error while running the stimela basic reduction pipeline, tracing down to the source now.

Plotting calibration solutions with MSUtils gives an error in Python 3, because as defined in `imp_plotter.py` : 
`nsols  = Gsols.shape[0]/N_ants` produces a float, causing in error later on when it's supposed to be an integer.

**Comment by KshitijT** [comment]
@JonahDW , could you specify which dataset are you using ? And the traceback?

**Comment by JonahDW** [comment]
The dataset I'm using is the DEEP2 dataset, from the 'Basic MeerKAT reduction' tutorial on the Stimela github page. The recipe add is specified as
```
recipe.add("cab/msutils", "plot_delays", {
    "command": "plot_gains",
    "ctable": "1491291289.K0:output",
    "tabtype": "delay",
    "plot_file": "delays.png",
    "subplot_scale": 4,
    "plot_dpi": 180,
}, input=INPUT, output=OUTPUT, label="plot delays")
```
To plot the calibration solutions. The traceback (preceded by some output) reads then
```
# Successful readonly open of default-locked table /stimela_mount/output/1491291289.K0::ANTENNA: 8 columns, 16 rows
# Antennas present in the table: ['m000', 'm002', 'm005', 'm011', 'm012', 'm018', 'm020', 'm042', 'm049', 'm057', 'm058', 'm059'
, 'm060', 'm061', 'm062', 'm063']
# Number of Antennas to plot: 16
# Number of solutions per antenna: 132.0
# Shape of solutions: (2112, 1) (2112, 1)
# Number of plots: 25
# Traceback (most recent call last):
#   File "/stimela_mount/code/run.py", line 57, in <module>
#     gain_plotter(tab, tabtype, outfile, scale, dpi)
#   File "/usr/local/lib/python3.6/dist-packages/MSUtils/imp_plotter.py", line 369, in gain_plotter
#     plot_delay_table(caltable,plt_scale,plt_dpi,outfile)
#   File "/usr/local/lib/python3.6/dist-packages/MSUtils/imp_plotter.py", line 344, in plot_delay_table
#     for sol in range(nsols):
# TypeError: 'float' object cannot be interpreted as an integer
```
Clearly the number of solutions should not be 132.0, as is stated in the output, I'm fairly convinced this causes the error.
