### ISSUE TITLE
add tool to estimate spectral weights

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/msutils#6]
Inherited from [meerkathi](https://github.com/ska-sa/meerkathi/issues/121)

A tool to estimate spectral weights
- Mode 1: Use spec. sensitivity values (must be provided by user)
- Mode 2: Use estimates of visibility noise. In this case, the difference of adjacent channels gives a good estimate of the noise, when using a calibrator field after 1GC. May also get good results by the cross correlations (XY, YX) , or maybe even STOKES V

**Comment by sphemakh** [comment]
@o-smirnov this is the module I'm using for this https://github.com/SpheMakh/msutils/tree/master/MSUtils

For now it will estimate weights given noise stats as a function of frequency. For MeerKAT you can get the weights as follows

```
import MSUtils.ClassESW as esw
msnoise = esw.MSNoise(<msname>)
noise, weights = msnoise.estimate_weights(stats_data=esw.MEERKAT_SEFD)
msnoise.write_toms(noise, columns=['SIGMA', 'SIGMA_SPECTRUM'])
msnoise.write_toms(weights, columns=['WEIGHT', 'WEIGHT_SPECTRUM'])
```

The MeerKAT noise data is stored in `esw.MEERKAT_SEFD`

**Comment by sphemakh** [comment]
NOTE: Must loop over spectral window IDs. The current setup will fail when on multiple SPWs with varying SPW channels
